export const defaultTheme = {
  base: {
    white: '#FFFFFF',
    background: '#FAFAFA',
    'background-body': '#DEDEDE',
    title: '#272221',
    subtitle: '#403937',
    text: '#574F4D',
    'base-label': '#8D8686',
    'base-hover': '#D7D5D5',
    'base-button': '#E6E5E5',
    'base-input': '#EDEDED',
    'base-card': '#F3F2F2',
  },
  products: {
    yellow: '#DBAC2C',
    purple: '#8047F8',
    'yellow-dark': '#C47F17',
    'yellow-light': '#F1E9C9',
    'purple-dark': '#4B2995',
    'purple-light': '#EBE5F9',
  },
  classes: {
    'text-regular-S': 'text-regular-S',
    'text-regular-M': 'text-regular-M',
    'text-regular-L': 'text-regular-L',
    'text-bold-M': 'text-bold-M',
    'text-bold-L': 'text-bold-L',
    'title-XS': 'title-XS',
    'title-S': 'title-S',
    'title-L': 'title-L',
    'title-XL': 'title-XL',
    'text-required': 'text-required',
  },
}
